version: '3.3'
services:
  ndless-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ndless-dev
    container_name: ndless-dev
    volumes:
      - type: bind
        source: ./src
        target: /opt/ndless-dev/src
    stdin_open: true
    tty: true
